In [2]:
import pandas as pd
import numpy as np
import json 
import requests

In [ ]:
PIB_per_capita = 'NY.GDP.PCAP.CD'

In [4]:
#Construir la consulta al banco mundial
url = 'http://api.worldbank.org/v2/country/all/indicator/{}'
params = {
    'format': 'json',
    'date': '2010:2022',
    'per_page': '30000'
}

In [5]:
respuesta = requests.get(url.format('NY.GDP.PCAP.CD'), params=params)

In [7]:
respuesta.json

In [8]:
respuesta.json()

[{'page': 1,
  'pages': 1,
  'per_page': 30000,
  'total': 3458,
  'sourceid': '2',
  'lastupdated': '2025-07-01'},
 [{'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2022',
   'value': 1628.31894446307,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2021',
   'value': 1522.3933455926,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2020',
   'value': 1344.10320999294,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2019',
   'value': 1493.81793829992,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2018',
   'value': 1538.90167917284,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2017',
   'value': 1520.21223076132,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2016',
   'value': 1329.80728479234,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2015',
   'value': 1479.61525980543,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2014',
   'value': 1656.16770915726,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2013',
   'value': 1673.22110186487,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2012',
   'value': 1702.9691001504,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2011',
   'value': 1735.58492331253,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
   'countryiso3code': 'AFE',
   'date': '2010',
   'value': 1601.72765054704,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2022',
   'value': 1796.66863273368,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2021',
   'value': 1765.9547879785,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2020',
   'value': 1680.03933212698,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2019',
   'value': 1798.34068458315,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2018',
   'value': 1720.14027955102,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2017',
   'value': 1574.23056047232,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2016',
   'value': 1630.03944681121,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2015',
   'value': 1860.72769393488,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2014',
   'value': 2221.01066549765,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2013',
   'value': 2131.66206746081,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2012',
   'value': 1941.36955612659,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2011',
   'value': 1844.1985949993,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
   'countryiso3code': 'AFW',
   'date': '2010',
   'value': 1663.96693663873,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2022',
   'value': 7931.61789279006,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2021',
   'value': 6681.70895180141,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2020',
   'value': 5722.48099531674,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2019',
   'value': 6638.48541455372,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2018',
   'value': 6668.2167280195,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2017',
   'value': 6066.72679100576,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2016',
   'value': 6012.51244365971,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2015',
   'value': 6262.04168490023,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2014',
   'value': 7311.28996894347,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2013',
   'value': 7351.94811264419,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2012',
   'value': 7362.6299087983,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2011',
   'value': 6894.19536785393,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': '1A', 'value': 'Arab World'},
   'countryiso3code': 'ARB',
   'date': '2010',
   'value': 5928.30535993301,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2022',
   'value': 17355.8366579795,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2021',
   'value': 13833.3099303464,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2020',
   'value': 11925.7573950011,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2019',
   'value': 13938.2023201976,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2018',
   'value': 13815.3265154798,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2017',
   'value': 13637.1207205804,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2016',
   'value': 13297.7443496162,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2015',
   'value': 14402.4725779389,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2014',
   'value': 14888.5440422155,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2013',
   'value': 14504.715597077,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2012',
   'value': 14172.8904656639,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2011',
   'value': 13449.4807692589,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'S3', 'value': 'Caribbean small states'},
   'countryiso3code': 'CSS',
   'date': '2010',
   'value': 12594.873505728,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2022',
   'value': 19548.6930479638,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2021',
   'value': 19239.8185020397,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2020',
   'value': 16595.9352698049,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2019',
   'value': 16551.8488917344,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2018',
   'value': 16245.193864543,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2017',
   'value': 14339.8580613846,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2016',
   'value': 12874.7406922285,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2015',
   'value': 12596.9475064792,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2014',
   'value': 14208.4595197236,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2013',
   'value': 13712.7336488743,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2012',
   'value': 13104.103611889,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2011',
   'value': 13997.441472478,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
   'countryiso3code': 'CEB',
   'date': '2010',
   'value': 12635.8166890856,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
   'countryiso3code': 'EAR',
   'date': '2022',
   'value': 4113.00084852322,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
   'countryiso3code': 'EAR',
   'date': '2021',
   'value': 3765.51079786712,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
   'countryiso3code': 'EAR',
   'date': '2020',
   'value': 3250.74974734387,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
   'countryiso3code': 'EAR',
   'date': '2019',
   'value': 3543.32390703605,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',
    'value': 'GDP per capita (current US$)'},
   'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
   'countryiso3code': 'EAR',
   'date': '2018',
   'value': 3515.76621670583,
   'unit': '',
   'obs_status': '',
   'decimal': 1},
  {'indicator': {'id': 'NY.GDP.PCAP.CD',

In [9]:
PIB = respuesta.json()

In [10]:
print(len(PIB))

2

In [11]:
PIB[0]

{'page': 1,
 'pages': 1,
 'per_page': 30000,
 'total': 3458,
 'sourceid': '2',
 'lastupdated': '2025-07-01'}

In [12]:
PIB[1]

[{'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2022',
  'value': 1628.31894446307,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2021',
  'value': 1522.3933455926,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2020',
  'value': 1344.10320999294,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2019',
  'value': 1493.81793829992,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2018',
  'value': 1538.90167917284,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2017',
  'value': 1520.21223076132,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2016',
  'value': 1329.80728479234,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2015',
  'value': 1479.61525980543,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2014',
  'value': 1656.16770915726,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2013',
  'value': 1673.22110186487,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2012',
  'value': 1702.9691001504,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2011',
  'value': 1735.58492331253,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZH', 'value': 'Africa Eastern and Southern'},
  'countryiso3code': 'AFE',
  'date': '2010',
  'value': 1601.72765054704,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2022',
  'value': 1796.66863273368,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2021',
  'value': 1765.9547879785,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2020',
  'value': 1680.03933212698,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2019',
  'value': 1798.34068458315,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2018',
  'value': 1720.14027955102,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2017',
  'value': 1574.23056047232,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2016',
  'value': 1630.03944681121,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2015',
  'value': 1860.72769393488,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2014',
  'value': 2221.01066549765,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2013',
  'value': 2131.66206746081,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2012',
  'value': 1941.36955612659,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2011',
  'value': 1844.1985949993,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'ZI', 'value': 'Africa Western and Central'},
  'countryiso3code': 'AFW',
  'date': '2010',
  'value': 1663.96693663873,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2022',
  'value': 7931.61789279006,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2021',
  'value': 6681.70895180141,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2020',
  'value': 5722.48099531674,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2019',
  'value': 6638.48541455372,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2018',
  'value': 6668.2167280195,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2017',
  'value': 6066.72679100576,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2016',
  'value': 6012.51244365971,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2015',
  'value': 6262.04168490023,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2014',
  'value': 7311.28996894347,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2013',
  'value': 7351.94811264419,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2012',
  'value': 7362.6299087983,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2011',
  'value': 6894.19536785393,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': '1A', 'value': 'Arab World'},
  'countryiso3code': 'ARB',
  'date': '2010',
  'value': 5928.30535993301,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2022',
  'value': 17355.8366579795,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2021',
  'value': 13833.3099303464,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2020',
  'value': 11925.7573950011,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2019',
  'value': 13938.2023201976,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2018',
  'value': 13815.3265154798,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2017',
  'value': 13637.1207205804,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2016',
  'value': 13297.7443496162,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2015',
  'value': 14402.4725779389,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2014',
  'value': 14888.5440422155,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2013',
  'value': 14504.715597077,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2012',
  'value': 14172.8904656639,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2011',
  'value': 13449.4807692589,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'S3', 'value': 'Caribbean small states'},
  'countryiso3code': 'CSS',
  'date': '2010',
  'value': 12594.873505728,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2022',
  'value': 19548.6930479638,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2021',
  'value': 19239.8185020397,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2020',
  'value': 16595.9352698049,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2019',
  'value': 16551.8488917344,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2018',
  'value': 16245.193864543,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2017',
  'value': 14339.8580613846,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2016',
  'value': 12874.7406922285,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2015',
  'value': 12596.9475064792,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2014',
  'value': 14208.4595197236,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2013',
  'value': 13712.7336488743,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2012',
  'value': 13104.103611889,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2011',
  'value': 13997.441472478,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'B8', 'value': 'Central Europe and the Baltics'},
  'countryiso3code': 'CEB',
  'date': '2010',
  'value': 12635.8166890856,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2022',
  'value': 4113.00084852322,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2021',
  'value': 3765.51079786712,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2020',
  'value': 3250.74974734387,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2019',
  'value': 3543.32390703605,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2018',
  'value': 3515.76621670583,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2017',
  'value': 3505.10621501561,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2016',
  'value': 3269.98432817621,
  'unit': '',
  'obs_status': '',
  'decimal': 1},
 {'indicator': {'id': 'NY.GDP.PCAP.CD',
   'value': 'GDP per capita (current US$)'},
  'country': {'id': 'V2', 'value': 'Early-demographic dividend'},
  'countryiso3code': 'EAR',
  'date': '2015',
  'value': 3219.68827173818,
  'unit': '',
  'obs_status': '',

In [13]:
Indicadores = PIB[1]

In [14]:
df = pd.DataFrame(Indicadores)

In [16]:
df.columns

Index(['indicator', 'country', 'countryiso3code', 'date', 'value', 'unit',
       'obs_status', 'decimal'],
      dtype='object')

In [17]:
df = df[["country", "date", "value"]]

In [18]:
df

                                                country  date        value
0     {'id': 'ZH', 'value': 'Africa Eastern and Sout...  2022  1628.318944
1     {'id': 'ZH', 'value': 'Africa Eastern and Sout...  2021  1522.393346
2     {'id': 'ZH', 'value': 'Africa Eastern and Sout...  2020  1344.103210
3     {'id': 'ZH', 'value': 'Africa Eastern and Sout...  2019  1493.817938
4     {'id': 'ZH', 'value': 'Africa Eastern and Sout...  2018  1538.901679
...                                                 ...   ...          ...
3453                  {'id': 'ZW', 'value': 'Zimbabwe'}  2014  1372.214746
3454                  {'id': 'ZW', 'value': 'Zimbabwe'}  2013  1362.299529
3455                  {'id': 'ZW', 'value': 'Zimbabwe'}  2012  1238.594795
3456                  {'id': 'ZW', 'value': 'Zimbabwe'}  2011  1037.246137
3457                  {'id': 'ZW', 'value': 'Zimbabwe'}  2010   901.550518

[3458 rows x 3 columns]

In [40]:
df.head()

,country,date,value,country_name
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2022,1628.318944,Africa Eastern and Southern
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2021,1522.393346,Africa Eastern and Southern
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2020,1344.103210,Africa Eastern and Southern
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2019,1493.817938,Africa Eastern and Southern
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2018,1538.901679,Africa Eastern and Southern

In [20]:
df.describe()

               value
count    3369.000000
mean    16912.003647
std     25331.313163
min       210.008140
25%      2082.629890
50%      6517.954322
75%     20818.614609
max    226052.001905

In [22]:
df.size, df.shape

(10374, (3458, 3))

In [23]:
df["country_name"] = 0

/var/folders/hv/cskfmpx94yz2kwd1_cq7ctxc0000gn/T/ipykernel_5609/3852765813.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country_name"] = 0

In [32]:
df.loc[0]["country"]["value"]

'Africa Eastern and Southern'

In [33]:
df["country_name"] = df["country"].apply(lambda fila: fila["value"])

/var/folders/hv/cskfmpx94yz2kwd1_cq7ctxc0000gn/T/ipykernel_5609/162092561.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["country_name"] = df["country"].apply(lambda fila: fila["value"])

In [34]:
df

,country,date,value,country_name
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2022,1628.318944,Africa Eastern and Southern
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2021,1522.393346,Africa Eastern and Southern
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2020,1344.103210,Africa Eastern and Southern
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2019,1493.817938,Africa Eastern and Southern
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2018,1538.901679,Africa Eastern and Southern
...,...,...,...,...
3453,"{'id': 'ZW', 'value': 'Zimbabwe'}",2014,1372.214746,Zimbabwe
3454,"{'id': 'ZW', 'value': 'Zimbabwe'}",2013,1362.299529,Zimbabwe
3455,"{'id': 'ZW', 'value': 'Zimbabwe'}",2012,1238.594795,Zimbabwe
3456,"{'id': 'ZW', 'value': 'Zimbabwe'}",2011,1037.246137,Zimbabwe
3457,"{'id': 'ZW', 'value': 'Zimbabwe'}",2010,901.550518,Zimbabwe

In [39]:
df[df["country_name"] == "Ecuador"].describe()

             value
count    13.000000
mean   5884.601967
std     562.478788
min    4520.309590
25%    5634.083932
50%    6061.323502
75%    6233.322448
max    6515.585284

In [41]:
df[df["country_name"] == "Argentina"]

                                country  date         value country_name
728  {'id': 'AR', 'value': 'Argentina'}  2022  13935.681111    Argentina
729  {'id': 'AR', 'value': 'Argentina'}  2021  10738.017922    Argentina
730  {'id': 'AR', 'value': 'Argentina'}  2020   8535.599380    Argentina
731  {'id': 'AR', 'value': 'Argentina'}  2019   9955.974787    Argentina
732  {'id': 'AR', 'value': 'Argentina'}  2018  11752.799892    Argentina
733  {'id': 'AR', 'value': 'Argentina'}  2017  14532.500931    Argentina
734  {'id': 'AR', 'value': 'Argentina'}  2016  12699.962314    Argentina
735  {'id': 'AR', 'value': 'Argentina'}  2015  13679.626498    Argentina
736  {'id': 'AR', 'value': 'Argentina'}  2014  12233.144412    Argentina
737  {'id': 'AR', 'value': 'Argentina'}  2013  12963.675773    Argentina
738  {'id': 'AR', 'value': 'Argentina'}  2012  12949.717487    Argentina
739  {'id': 'AR', 'value': 'Argentina'}  2011  12704.283182    Argentina
740  {'id': 'AR', 'value': 'Argentina'}  2010  10260.131311    Argentina

In [48]:
paises = ["Ecuador", "Peru", "Japan"]

In [49]:
df[df["country_name"].isin(paises)]

                               country  date         value country_name
1378  {'id': 'EC', 'value': 'Ecuador'}  2022   6515.585284      Ecuador
1379  {'id': 'EC', 'value': 'Ecuador'}  2021   6061.323502      Ecuador
1380  {'id': 'EC', 'value': 'Ecuador'}  2020   5463.645153      Ecuador
1381  {'id': 'EC', 'value': 'Ecuador'}  2019   6205.057652      Ecuador
1382  {'id': 'EC', 'value': 'Ecuador'}  2018   6303.918867      Ecuador
1383  {'id': 'EC', 'value': 'Ecuador'}  2017   6233.322448      Ecuador
1384  {'id': 'EC', 'value': 'Ecuador'}  2016   5917.637713      Ecuador
1385  {'id': 'EC', 'value': 'Ecuador'}  2015   5976.159681      Ecuador
1386  {'id': 'EC', 'value': 'Ecuador'}  2014   6405.799793      Ecuador
1387  {'id': 'EC', 'value': 'Ecuador'}  2013   6109.290315      Ecuador
1388  {'id': 'EC', 'value': 'Ecuador'}  2012   5634.083932      Ecuador
1389  {'id': 'EC', 'value': 'Ecuador'}  2011   5153.691642      Ecuador
1390  {'id': 'EC', 'value': 'Ecuador'}  2010   4520.309590      Ecuador
1911    {'id': 'JP', 'value': 'Japan'}  2022  34065.643896        Japan
1912    {'id': 'JP', 'value': 'Japan'}  2021  40094.559980        Japan
1913    {'id': 'JP', 'value': 'Japan'}  2020  40028.734173        Japan
1914    {'id': 'JP', 'value': 'Japan'}  2019  40415.956765        Japan
1915    {'id': 'JP', 'value': 'Japan'}  2018  39751.133098        Japan
1916    {'id': 'JP', 'value': 'Japan'}  2017  38834.052934        Japan
1917    {'id': 'JP', 'value': 'Japan'}  2016  39375.473162        Japan
1918    {'id': 'JP', 'value': 'Japan'}  2015  34960.639384        Japan
1919    {'id': 'JP', 'value': 'Japan'}  2014  38475.395246        Japan
1920    {'id': 'JP', 'value': 'Japan'}  2013  40898.647896        Japan
1921    {'id': 'JP', 'value': 'Japan'}  2012  49145.280431        Japan
1922    {'id': 'JP', 'value': 'Japan'}  2011  48760.078949        Japan
1923    {'id': 'JP', 'value': 'Japan'}  2010  44968.156235        Japan
2639     {'id': 'PE', 'value': 'Peru'}  2022   7350.630343         Peru
2640     {'id': 'PE', 'value': 'Peru'}  2021   6826.202556         Peru
2641     {'id': 'PE', 'value': 'Peru'}  2020   6133.325524         Peru
2642     {'id': 'PE', 'value': 'Peru'}  2019   7037.008037         Peru
2643     {'id': 'PE', 'value': 'Peru'}  2018   6978.491215         Peru
2644     {'id': 'PE', 'value': 'Peru'}  2017   6736.166937         Peru
2645     {'id': 'PE', 'value': 'Peru'}  2016   6217.036000         Peru
2646     {'id': 'PE', 'value': 'Peru'}  2015   6231.711503         Peru
2647     {'id': 'PE', 'value': 'Peru'}  2014   6667.134104         Peru
2648     {'id': 'PE', 'value': 'Peru'}  2013   6746.800257         Peru
2649     {'id': 'PE', 'value': 'Peru'}  2012   6519.378530         Peru
2650     {'id': 'PE', 'value': 'Peru'}  2011   5861.357936         Peru
2651     {'id': 'PE', 'value': 'Peru'}  2010   5072.114940         Peru

In [55]:
df[(df["date"] == "2020") & (df["country_name"] == "Ecuador")]

                               country  date        value country_name
1380  {'id': 'EC', 'value': 'Ecuador'}  2020  5463.645153      Ecuador

In [58]:
PIB_EC = ["2021", "2022"]

In [68]:
df[(df["date"].isin(PIB_EC)) & (df["country_name"] == "Ecuador")]["value"].mean()

np.float64(6288.454393000235)

In [75]:
df[df["value"] == df["value"].max()]["country_name"]

2327    Monaco
Name: country_name, dtype: object

In [79]:
df[df["value"]> 20000]["country_name"].unique()

array(['Euro area', 'Europe & Central Asia', 'European Union',
       'High income', 'North America', 'OECD members',
       'Post-demographic dividend', 'Andorra', 'Antigua and Barbuda',
       'Aruba', 'Australia', 'Austria', 'Bahamas, The', 'Bahrain',
       'Barbados', 'Belgium', 'Bermuda', 'Brunei Darussalam', 'Canada',
       'Cayman Islands', 'Channel Islands', 'Curacao', 'Cyprus',
       'Czechia', 'Denmark', 'Estonia', 'Faroe Islands', 'Finland',
       'France', 'French Polynesia', 'Germany', 'Greece', 'Greenland',
       'Guam', 'Hong Kong SAR, China', 'Iceland', 'Ireland',
       'Isle of Man', 'Israel', 'Italy', 'Japan', 'Korea, Rep.', 'Kuwait',
       'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Macao SAR, China', 'Malta', 'Monaco', 'Netherlands',
       'New Caledonia', 'New Zealand', 'Northern Mariana Islands',
       'Norway', 'Oman', 'Portugal', 'Puerto Rico (US)', 'Qatar',
       'San Marino', 'Saudi Arabia', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Spain', 'St. Kitts and Nevis', 'St. Martin (French part)',
       'Sweden', 'Switzerland', 'Trinidad and Tobago',
       'Turks and Caicos Islands', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay',
       'Virgin Islands (U.S.)'], dtype=object)

In [80]:
df

,country,date,value,country_name
0,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2022,1628.318944,Africa Eastern and Southern
1,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2021,1522.393346,Africa Eastern and Southern
2,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2020,1344.103210,Africa Eastern and Southern
3,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2019,1493.817938,Africa Eastern and Southern
4,"{'id': 'ZH', 'value': 'Africa Eastern and Sout...",2018,1538.901679,Africa Eastern and Southern
...,...,...,...,...
3453,"{'id': 'ZW', 'value': 'Zimbabwe'}",2014,1372.214746,Zimbabwe
3454,"{'id': 'ZW', 'value': 'Zimbabwe'}",2013,1362.299529,Zimbabwe
3455,"{'id': 'ZW', 'value': 'Zimbabwe'}",2012,1238.594795,Zimbabwe
3456,"{'id': 'ZW', 'value': 'Zimbabwe'}",2011,1037.246137,Zimbabwe
3457,"{'id': 'ZW', 'value': 'Zimbabwe'}",2010,901.550518,Zimbabwe

In [87]:
df.sort_values("value", ascending=False).head(7)["country_name"].unique().tolist()

['Monaco', 'Liechtenstein']

In [89]:
South_america = ["Argentina", "Colombia", "Brazil", "Peru", "Ecuador", "Chile"]

In [105]:
df[df["country_name"].isin(South_america)].sort_values("value", ascending=False).head()["country_name"].unique().tolist()

['Chile']

In [115]:
df.groupby("country_name")["value"].max().sort_values(ascending=False).head()

country_name
Monaco           226052.001905
Liechtenstein    201944.830335
Luxembourg       134965.815442
Bermuda          121613.939984
Norway           109269.520580
Name: value, dtype: float64